#!/usr/bin/env bash
# One-command install of a Vantage hosted range on a fresh Ubuntu 22.04/24.04 VM
# (4 GB RAM is enough for ~3 parallel incidents; Oracle Cloud Free Tier ARM works).
#
#   curl -fsSL https://raw.githubusercontent.com/krzys167-crypto/Vantage-v0.3/main/deploy/install.sh | \
#     sudo bash -s -- --domain range.example.com --supabase https://<ref>.supabase.co --supabase-key sb_publishable_...
#
# What you get:
#   https://<domain>/        panel (Supabase login, start incident, kubeconfig, grade, profile, league)
#   https://<domain>/v1/...  grader (signed results, pubkey for verification)
#   <domain>:6443            Kubernetes API for trainees (scoped per-session kubeconfigs)
# Needs: a DNS A record for <domain> pointing at this VM, ports 80/443/6443 open.
# Only PUBLIC Supabase values are used: the project URL and the publishable key.
# Never pass the secret/service-role key here.
set -euo pipefail

DOMAIN="" SUPABASE="" SUPABASE_KEY="" REPO="https://github.com/krzys167-crypto/Vantage-v0.3.git" REF="main"
MAX_SESSIONS=3 DRY=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain) DOMAIN="$2"; shift 2 ;;
    --supabase) SUPABASE="${2%/}"; shift 2 ;;
    --supabase-key) SUPABASE_KEY="$2"; shift 2 ;;
    --repo) REPO="$2"; shift 2 ;;
    --ref) REF="$2"; shift 2 ;;
    --max-sessions) MAX_SESSIONS="$2"; shift 2 ;;
    --dry-run) DRY=1; shift ;;
    *) echo "unknown option $1" >&2; exit 2 ;;
  esac
done
[[ -n "$DOMAIN" && -n "$SUPABASE" && -n "$SUPABASE_KEY" ]] || {
  echo "usage: install.sh --domain <fqdn> --supabase https://<ref>.supabase.co --supabase-key <publishable key>" >&2; exit 2; }
[[ "$SUPABASE_KEY" == sb_secret_* || "$SUPABASE_KEY" == *service_role* ]] && {
  echo "that is a SECRET key: pass the publishable one (sb_publishable_...)" >&2; exit 2; }
[[ "$DOMAIN" =~ ^[a-zA-Z0-9.-]+$ ]] || { echo "bad domain" >&2; exit 2; }

run() { if [[ $DRY == 1 ]]; then echo "+ $*"; else "$@"; fi; }
log() { printf '\033[36m==>\033[0m %s\n' "$*"; }
[[ $DRY == 1 || $EUID == 0 ]] || { echo "run as root (sudo)" >&2; exit 1; }

APP=/opt/vantage DATA=/var/lib/vantage ENVF=/etc/vantage/env
arch="$(dpkg --print-architecture 2>/dev/null || echo amd64)"

log "packages: docker, git, python3, openssl, caddy"
run apt-get update -qq
run apt-get install -y -qq ca-certificates curl git python3 openssl debian-keyring debian-archive-keyring apt-transport-https ufw
command -v docker >/dev/null || run sh -c "curl -fsSL https://get.docker.com | sh"
if ! command -v caddy >/dev/null; then
  run sh -c "curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/gpg.key | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg"
  run sh -c "curl -1sLf https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt > /etc/apt/sources.list.d/caddy-stable.list"
  run apt-get update -qq && run apt-get install -y -qq caddy
fi
command -v k3d >/dev/null || run sh -c "curl -sSfL https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.7.4 bash"
command -v kubectl >/dev/null || {
  run curl -sSfLo /usr/local/bin/kubectl "https://dl.k8s.io/release/v1.31.0/bin/linux/$arch/kubectl"
  run chmod +x /usr/local/bin/kubectl; }

log "user and code: $APP ($REF)"
id vantage >/dev/null 2>&1 || run useradd --system --create-home --groups docker --shell /usr/sbin/nologin vantage
if [[ -d $APP/.git ]]; then run git -C "$APP" fetch -q origin "$REF"; run git -C "$APP" checkout -q -B "$REF" "origin/$REF"
else run git clone -q --branch "$REF" "$REPO" "$APP"; fi
run mkdir -p "$DATA/grader" "$DATA/sessions" /etc/vantage
run chown -R vantage: "$APP" "$DATA"

log "k3d cluster (API on :6443, certificate valid for $DOMAIN)"
if ! run sudo -u vantage k3d cluster list vantage >/dev/null 2>&1; then
  run sudo -u vantage k3d cluster create vantage --agents 1 --no-lb --wait \
    --api-port 0.0.0.0:6443 --k3s-arg "--tls-san=$DOMAIN@server:0"
fi
run sudo -u vantage bash "$APP/framework/k3d_preload.sh" vantage

log "configuration: $ENVF (public values + generated platform token)"
if [[ ! -f $ENVF ]]; then
  token="$(openssl rand -hex 24)" admin="$(openssl rand -hex 24)"
  [[ $DRY == 1 ]] || cat > "$ENVF" <<EOT
# generated by deploy/install.sh; public Supabase values only
GRADER_URL=http://127.0.0.1:8700
GRADER_JWKS_URL=$SUPABASE/auth/v1/.well-known/jwks.json
GRADER_JWT_ISSUER=$SUPABASE/auth/v1
GRADER_PLATFORM_TOKEN=$token
RANGE_PLATFORM_TOKEN=$token
PANEL_SUPABASE_URL=$SUPABASE
PANEL_SUPABASE_KEY=$SUPABASE_KEY
RANGE_PUBLIC_API=https://$DOMAIN:6443
RANGE_SESSIONS=$DATA/sessions
RANGE_MAX_SESSIONS=$MAX_SESSIONS
RANGE_ADMIN_TOKEN=$admin
KUBE_CONTEXT=k3d-vantage
HOME=/home/vantage
EOT
  run chmod 640 "$ENVF"; run chown root:vantage "$ENVF"
fi

log "services: vantage-grader, vantage-range-api"
unit() { # name exec
  [[ $DRY == 1 ]] && { echo "+ unit $1: $2"; return; }
  cat > "/etc/systemd/system/$1.service" <<EOT
[Unit]
Description=$1
After=network-online.target docker.service
Wants=network-online.target
[Service]
User=vantage
EnvironmentFile=$ENVF
WorkingDirectory=$APP
ExecStart=$2
Restart=always
RestartSec=3
NoNewPrivileges=true
ProtectSystem=full
[Install]
WantedBy=multi-user.target
EOT
}
unit vantage-grader "/usr/bin/python3 $APP/grader/server.py --port 8700 --data $DATA/grader"
unit vantage-range-api "/usr/bin/python3 $APP/range/api.py --port 8780"
run systemctl daemon-reload
run systemctl enable --now vantage-grader vantage-range-api

log "HTTPS: Caddy for $DOMAIN (Let's Encrypt)"
[[ $DRY == 1 ]] || cat > /etc/caddy/Caddyfile <<EOT
$DOMAIN {
  encode gzip
  handle /v1/* {
    reverse_proxy 127.0.0.1:8700
  }
  handle {
    reverse_proxy 127.0.0.1:8780
  }
}
EOT
run systemctl reload-or-restart caddy

log "firewall: 22, 80, 443, 6443"
for p in 22 80 443 6443; do run ufw allow "$p/tcp" >/dev/null; done
run ufw --force enable >/dev/null

log "done: https://$DOMAIN  (grader public key: https://$DOMAIN/v1/pubkey)"
echo "Supabase: Authentication -> URL Configuration -> add https://$DOMAIN to Redirect URLs."
echo "Funnel (where trainees get stuck): curl -s -H \"X-Admin-Token: \$(sudo grep -oP '(?<=RANGE_ADMIN_TOKEN=).*' $ENVF)\" https://$DOMAIN/api/admin/funnel?days=30"
